/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Comentarios: typeof import('./src/components/comentarios.vue')['default']
    Contato: typeof import('./src/components/contato.vue')['default']
    Equipe: typeof import('./src/components/equipe.vue')['default']
    Especialidades: typeof import('./src/components/especialidades.vue')['default']
    Footers: typeof import('./src/components/Footers.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Local: typeof import('./src/components/local.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    PreLoader: typeof import('./src/components/PreLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sobre: typeof import('./src/components/sobre.vue')['default']
  }
}
